In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import gmaps
import os
from scipy.stats import linregress
from citipy import citipy
import json
from pprint import pprint 
from datetime import datetime

output_data = "output_data/clean_covid.csv"

In [2]:
covid_df = pd.DataFrame(columns = ['Date'])

In [3]:
states = ["ca", "tx", "sd", "md", "ga", "fl"]

index = 0
 

for state in states:
    
    url = f"https://api.covidtracking.com/v1/states/{state}/daily.json"
    
    response = requests.get(url)
    response_json = response.json()
    
    for row in response_json:
        
        try:
            print(f"Printing data for {state} and index: {index}")

            
            covid_df.loc[index, 'Date'] = row['date']
            covid_df.loc[index, 'State'] = row['state']
            covid_df.loc[index, 'Positive'] = row['positive']
            covid_df.loc[index, 'Positive Increase'] = row['positiveIncrease']
            covid_df.loc[index, 'Death Increase'] = row['deathIncrease']
            covid_df.loc[index, 'Death Confirmed'] = row['death']
            covid_df.loc[index, 'Death Probable'] = row['deathProbable']
            covid_df.loc[index, 'Hospitalized'] = row['hospitalized']
            covid_df.loc[index, 'Negative'] = row['negative']
            covid_df.loc[index, 'Recovered'] = row['recovered']
            covid_df.loc[index, 'Total'] = row['total']
            covid_df.loc[index, 'Total Test Results'] = row['totalTestResults']
           
            index += 1
           

        except (KeyError, IndexError):
            print("info not found. Skipping....")

Printing data for ca and index: 0
Printing data for ca and index: 1
Printing data for ca and index: 2
Printing data for ca and index: 3
Printing data for ca and index: 4
Printing data for ca and index: 5
Printing data for ca and index: 6
Printing data for ca and index: 7
Printing data for ca and index: 8
Printing data for ca and index: 9
Printing data for ca and index: 10
Printing data for ca and index: 11
Printing data for ca and index: 12
Printing data for ca and index: 13
Printing data for ca and index: 14
Printing data for ca and index: 15
Printing data for ca and index: 16
Printing data for ca and index: 17
Printing data for ca and index: 18
Printing data for ca and index: 19
Printing data for ca and index: 20
Printing data for ca and index: 21
Printing data for ca and index: 22
Printing data for ca and index: 23
Printing data for ca and index: 24
Printing data for ca and index: 25
Printing data for ca and index: 26
Printing data for ca and index: 27
Printing data for ca and index: 28
Printing data for ca and index: 29
Printing data for ca and index: 30
Printing data for ca and index: 31
Printing data for ca and index: 32
Printing data for ca and index: 33
Printing data for ca and index: 34
Printing data for ca and index: 35
Printing data for ca and index: 36
Printing data for ca and index: 37
Printing data for ca and index: 38
Printing data for ca and index: 39
Printing data for ca and index: 40
Printing data for ca and index: 41
Printing data for ca and index: 42
Printing data for ca and index: 43
Printing data for ca and index: 44
Printing data for ca and index: 45
Printing data for ca and index: 46
Printing data for ca and index: 47
Printing data for ca and index: 48
Printing data for ca and index: 49
Printing data for ca and index: 50
Printing data for ca and index: 51
Printing data for ca and index: 52
Printing data for ca and index: 53
Printing data for ca and index: 54
Printing data for ca and index: 55
Printing data for ca and index: 56
Printing data for ca and index: 57
Printing data for ca and index: 58
Printing data for ca and index: 59
Printing data for ca and index: 60
Printing data for ca and index: 61
Printing data for ca and index: 62
Printing data for ca and index: 63
Printing data for ca and index: 64
Printing data for ca and index: 65
Printing data for ca and index: 66
Printing data for ca and index: 67
Printing data for ca and index: 68
Printing data for ca and index: 69
Printing data for ca and index: 70
Printing data for ca and index: 71
Printing data for ca and index: 72
Printing data for ca and index: 73
Printing data for ca and index: 74
Printing data for ca and index: 75
Printing data for ca and index: 76
Printing data for ca and index: 77
Printing data for ca and index: 78
Printing data for ca and index: 79
Printing data for ca and index: 80
Printing data for ca and index: 81
Printing data for ca and index: 82
Printing data for ca and index: 83
Printing data for ca and index: 84
Printing data for ca and index: 85
Printing data for ca and index: 86
Printing data for ca and index: 87
Printing data for ca and index: 88
Printing data for ca and index: 89
Printing data for ca and index: 90
Printing data for ca and index: 91
Printing data for ca and index: 92
Printing data for ca and index: 93
Printing data for ca and index: 94
Printing data for ca and index: 95
Printing data for ca and index: 96
Printing data for ca and index: 97
Printing data for ca and index: 98
Printing data for ca and index: 99
Printing data for ca and index: 100
Printing data for ca and index: 101
Printing data for ca and index: 102
Printing data for ca and index: 103
Printing data for ca and index: 104
Printing data for ca and index: 105
Printing data for ca and index: 106
Printing data for ca and index: 107
Printing data for ca and index: 108
Printing data for ca and index: 109
Printing data for ca and index: 110
Printing data for ca and index: 111
Printing data for ca and index: 112
Printing data for ca and index: 113
Printing data for ca and index: 114
Printing data for ca and index: 115
Printing data for ca and index: 116
Printing data for ca and index: 117
Printing data for ca and index: 118
Printing data for ca and index: 119
Printing data for ca and index: 120
Printing data for ca and index: 121
Printing data for ca and index: 122
Printing data for ca and index: 123
Printing data for ca and index: 124
Printing data for ca and index: 125
Printing data for ca and index: 126
Printing data for ca and index: 127
Printing data for ca and index: 128
Printing data for ca and index: 129
Printing data for ca and index: 130
Printing data for ca and index: 131
Printing data for ca and index: 132
Printing data for ca and index: 133
Printing data for ca and index: 134
Printing data for ca and index: 135
Printing data for ca and index: 136
Printing data for ca and index: 137
Printing data for ca and index: 138
Printing data for ca and index: 139
Printing data for ca and index: 140
Printing data for ca and index: 141
Printing data for ca and index: 142
Printing data for ca and index: 143
Printing data for ca and index: 144
Printing data for ca and index: 145
Printing data for ca and index: 146
Printing data for ca and index: 147
Printing data for ca and index: 148
Printing data for ca and index: 149
Printing data for ca and index: 150
Printing data for ca and index: 151
Printing data for ca and index: 152
Printing data for ca and index: 153
Printing data for ca and index: 154
Printing data for ca and index: 155
Printing data for ca and index: 156
Printing data for ca and index: 157
Printing data for ca and index: 158
Printing data for ca and index: 159
Printing data for ca and index: 160
Printing data for ca and index: 161
Printing data for ca and index: 162
Printing data for ca and index: 163
Printing data for ca and index: 164
Printing data for ca and index: 165
Printing data for ca and index: 166
Printing data for ca and index: 167
Printing data for ca and index: 168
Printing data for ca and index: 169
Printing data for ca and index: 170
Printing data for ca and index: 171
Printing data for ca and index: 172
Printing data for tx and index: 173
Printing data for tx and index: 174
Printing data for tx and index: 175
Printing data for tx and index: 176
Printing data for tx and index: 177
Printing data for tx and index: 178
Printing data for tx and index: 179
Printing data for tx and index: 180
Printing data for tx and index: 181
Printing data for tx and index: 182
Printing data for tx and index: 183
Printing data for tx and index: 184
Printing data for tx and index: 185
Printing data for tx and index: 186
Printing data for tx and index: 187
Printing data for tx and index: 188
Printing data for tx and index: 189
Printing data for tx and index: 190
Printing data for tx and index: 191
Printing data for tx and index: 192
Printing data for tx and index: 193
Printing data for tx and index: 194
Printing data for tx and index: 195
Printing data for tx and index: 196
Printing data for tx and index: 197
Printing data for tx and index: 198
Printing data for tx and index: 199
Printing data for tx and index: 200
Printing data for tx and index: 201
Printing data for tx and index: 202
Printing data for tx and index: 203
Printing data for tx and index: 204
Printing data for tx and index: 205
Printing data for tx and index: 206
Printing data for tx and index: 207
Printing data for tx and index: 208
Printing data for tx and index: 209
Printing data for tx and index: 210
Printing data for tx and index: 211
Printing data for tx and index: 212
Printing data for tx and index: 213
Printing data for tx and index: 214
Printing data for tx and index: 215
Printing data for tx and index: 216
Printing data for tx and index: 217
Printing data for tx and index: 218
Printing data for tx and index: 219
Printing data for tx and index: 220
Printing data for tx and index: 221
Printing data for tx and index: 222
Printing data for tx and index: 223
Printing data for tx and index: 224
Printing data for tx and index: 225
Printing data for tx and index: 226
Printing data for tx and index: 227
Printing data for tx and index: 228
Printing data for tx and index: 229
Printing data for tx and index: 230
Printing data for tx and index: 231
Printing data for tx and index: 232
Printing data for tx and index: 233
Printing data for tx and index: 234
Printing data for tx and index: 235
Printing data for tx and index: 236
Printing data for tx and index: 237

Printing data for tx and index: 238
Printing data for tx and index: 239
Printing data for tx and index: 240
Printing data for tx and index: 241
Printing data for tx and index: 242
Printing data for tx and index: 243
Printing data for tx and index: 244
Printing data for tx and index: 245
Printing data for tx and index: 246
Printing data for tx and index: 247
Printing data for tx and index: 248
Printing data for tx and index: 249
Printing data for tx and index: 250
Printing data for tx and index: 251
Printing data for tx and index: 252
Printing data for tx and index: 253
Printing data for tx and index: 254
Printing data for tx and index: 255
Printing data for tx and index: 256
Printing data for tx and index: 257
Printing data for tx and index: 258
Printing data for tx and index: 259
Printing data for tx and index: 260
Printing data for tx and index: 261
Printing data for tx and index: 262
Printing data for tx and index: 263
Printing data for tx and index: 264
Printing data for tx and index: 265
Printing data for tx and index: 266
Printing data for tx and index: 267
Printing data for tx and index: 268
Printing data for tx and index: 269
Printing data for tx and index: 270
Printing data for tx and index: 271
Printing data for tx and index: 272
Printing data for tx and index: 273
Printing data for tx and index: 274
Printing data for tx and index: 275
Printing data for tx and index: 276
Printing data for tx and index: 277
Printing data for tx and index: 278
Printing data for tx and index: 279
Printing data for tx and index: 280
Printing data for tx and index: 281
Printing data for tx and index: 282
Printing data for tx and index: 283
Printing data for tx and index: 284
Printing data for tx and index: 285
Printing data for tx and index: 286
Printing data for tx and index: 287
Printing data for tx and index: 288
Printing data for tx and index: 289
Printing data for tx and index: 290
Printing data for tx and index: 291
Printing data for tx and index: 292
Printing data for tx and index: 293
Printing data for tx and index: 294
Printing data for tx and index: 295
Printing data for tx and index: 296
Printing data for tx and index: 297
Printing data for tx and index: 298
Printing data for tx and index: 299
Printing data for tx and index: 300
Printing data for tx and index: 301
Printing data for tx and index: 302
Printing data for tx and index: 303
Printing data for tx and index: 304
Printing data for tx and index: 305
Printing data for tx and index: 306
Printing data for tx and index: 307
Printing data for tx and index: 308
Printing data for tx and index: 309
Printing data for tx and index: 310
Printing data for tx and index: 311
Printing data for tx and index: 312
Printing data for tx and index: 313
Printing data for tx and index: 314
Printing data for tx and index: 315
Printing data for tx and index: 316
Printing data for tx and index: 317
Printing data for tx and index: 318
Printing data for tx and index: 319
Printing data for tx and index: 320
Printing data for tx and index: 321
Printing data for tx and index: 322
Printing data for tx and index: 323
Printing data for tx and index: 324
Printing data for tx and index: 325
Printing data for tx and index: 326
Printing data for tx and index: 327
Printing data for tx and index: 328
Printing data for tx and index: 329
Printing data for tx and index: 330
Printing data for tx and index: 331
Printing data for tx and index: 332
Printing data for tx and index: 333
Printing data for tx and index: 334
Printing data for tx and index: 335
Printing data for tx and index: 336
Printing data for tx and index: 337
Printing data for tx and index: 338
Printing data for tx and index: 339
Printing data for tx and index: 340
Printing data for tx and index: 341
Printing data for tx and index: 342
Printing data for tx and index: 343
Printing data for tx and index: 344
Printing data for tx and index: 345
Printing data for sd and index: 346
Printing data for sd and index: 347
Printing data for sd and index: 348
Printing data for sd and index: 349
Printing data for sd and index: 350
Printing data for sd and index: 351
Printing data for sd and index: 352
Printing data for sd and index: 353
Printing data for sd and index: 354
Printing data for sd and index: 355
Printing data for sd and index: 356
Printing data for sd and index: 357
Printing data for sd and index: 358
Printing data for sd and index: 359
Printing data for sd and index: 360
Printing data for sd and index: 361
Printing data for sd and index: 362
Printing data for sd and index: 363
Printing data for sd and index: 364
Printing data for sd and index: 365
Printing data for sd and index: 366
Printing data for sd and index: 367
Printing data for sd and index: 368
Printing data for sd and index: 369
Printing data for sd and index: 370
Printing data for sd and index: 371
Printing data for sd and index: 372
Printing data for sd and index: 373
Printing data for sd and index: 374
Printing data for sd and index: 375
Printing data for sd and index: 376
Printing data for sd and index: 377
Printing data for sd and index: 378
Printing data for sd and index: 379
Printing data for sd and index: 380
Printing data for sd and index: 381
Printing data for sd and index: 382
Printing data for sd and index: 383
Printing data for sd and index: 384
Printing data for sd and index: 385
Printing data for sd and index: 386
Printing data for sd and index: 387
Printing data for sd and index: 388
Printing data for sd and index: 389
Printing data for sd and index: 390
Printing data for sd and index: 391
Printing data for sd and index: 392
Printing data for sd and index: 393
Printing data for sd and index: 394
Printing data for sd and index: 395
Printing data for sd and index: 396
Printing data for sd and index: 397
Printing data for sd and index: 398
Printing data for sd and index: 399
Printing data for sd and index: 400
Printing data for sd and index: 401
Printing data for sd and index: 402
Printing data for sd and index: 403
Printing data for sd and index: 404
Printing data for sd and index: 405
Printing data for sd and index: 406
Printing data for sd and index: 407
Printing data for sd and index: 408
Printing data for sd and index: 409
Printing data for sd and index: 410
Printing data for sd and index: 411
Printing data for sd and index: 412
Printing data for sd and index: 413
Printing data for sd and index: 414
Printing data for sd and index: 415
Printing data for sd and index: 416
Printing data for sd and index: 417
Printing data for sd and index: 418
Printing data for sd and index: 419
Printing data for sd and index: 420
Printing data for sd and index: 421
Printing data for sd and index: 422
Printing data for sd and index: 423
Printing data for sd and index: 424
Printing data for sd and index: 425
Printing data for sd and index: 426
Printing data for sd and index: 427
Printing data for sd and index: 428
Printing data for sd and index: 429
Printing data for sd and index: 430
Printing data for sd and index: 431
Printing data for sd and index: 432
Printing data for sd and index: 433
Printing data for sd and index: 434
Printing data for sd and index: 435
Printing data for sd and index: 436
Printing data for sd and index: 437
Printing data for sd and index: 438
Printing data for sd and index: 439
Printing data for sd and index: 440
Printing data for sd and index: 441
Printing data for sd and index: 442
Printing data for sd and index: 443
Printing data for sd and index: 444
Printing data for sd and index: 445
Printing data for sd and index: 446
Printing data for sd and index: 447
Printing data for sd and index: 448
Printing data for sd and index: 449
Printing data for sd and index: 450
Printing data for sd and index: 451
Printing data for sd and index: 452
Printing data for sd and index: 453
Printing data for sd and index: 454
Printing data for sd and index: 455
Printing data for sd and index: 456
Printing data for sd and index: 457
Printing data for sd and index: 458
Printing data for sd and index: 459
Printing data for sd and index: 460
Printing data for sd and index: 461
Printing data for sd and index: 462
Printing data for sd and index: 463
Printing data for sd and index: 464
Printing data for sd and index: 465
Printing data for sd and index: 466
Printing data for sd and index: 467
Printing data for sd and index: 468
Printing data for sd and index: 469
Printing data for sd and index: 470
Printing data for sd and index: 471
Printing data for sd and index: 472
Printing data for sd and index: 473
Printing data for sd and index: 474
Printing data for sd and index: 475
Printing data for sd and index: 476
Printing data for sd and index: 477
Printing data for sd and index: 478
Printing data for sd and index: 479
Printing data for sd and index: 480
Printing data for sd and index: 481

Printing data for sd and index: 482
Printing data for sd and index: 483
Printing data for sd and index: 484
Printing data for sd and index: 485
Printing data for sd and index: 486
Printing data for sd and index: 487
Printing data for sd and index: 488
Printing data for sd and index: 489
Printing data for sd and index: 490
Printing data for sd and index: 491
Printing data for sd and index: 492
Printing data for sd and index: 493
Printing data for sd and index: 494
Printing data for sd and index: 495
Printing data for sd and index: 496
Printing data for sd and index: 497
Printing data for sd and index: 498
Printing data for sd and index: 499
Printing data for sd and index: 500
Printing data for sd and index: 501
Printing data for sd and index: 502
Printing data for sd and index: 503
Printing data for sd and index: 504
Printing data for sd and index: 505
Printing data for sd and index: 506
Printing data for sd and index: 507
Printing data for sd and index: 508
Printing data for sd and index: 509
Printing data for sd and index: 510
Printing data for sd and index: 511
Printing data for sd and index: 512
Printing data for sd and index: 513
Printing data for sd and index: 514
Printing data for sd and index: 515
Printing data for md and index: 516
Printing data for md and index: 517
Printing data for md and index: 518
Printing data for md and index: 519
Printing data for md and index: 520
Printing data for md and index: 521
Printing data for md and index: 522
Printing data for md and index: 523
Printing data for md and index: 524
Printing data for md and index: 525
Printing data for md and index: 526
Printing data for md and index: 527
Printing data for md and index: 528
Printing data for md and index: 529
Printing data for md and index: 530
Printing data for md and index: 531
Printing data for md and index: 532
Printing data for md and index: 533
Printing data for md and index: 534
Printing data for md and index: 535
Printing data for md and index: 536
Printing data for md and index: 537
Printing data for md and index: 538
Printing data for md and index: 539
Printing data for md and index: 540
Printing data for md and index: 541
Printing data for md and index: 542
Printing data for md and index: 543
Printing data for md and index: 544
Printing data for md and index: 545
Printing data for md and index: 546
Printing data for md and index: 547
Printing data for md and index: 548
Printing data for md and index: 549
Printing data for md and index: 550
Printing data for md and index: 551
Printing data for md and index: 552
Printing data for md and index: 553
Printing data for md and index: 554
Printing data for md and index: 555
Printing data for md and index: 556
Printing data for md and index: 557
Printing data for md and index: 558
Printing data for md and index: 559
Printing data for md and index: 560
Printing data for md and index: 561
Printing data for md and index: 562
Printing data for md and index: 563
Printing data for md and index: 564
Printing data for md and index: 565
Printing data for md and index: 566
Printing data for md and index: 567
Printing data for md and index: 568
Printing data for md and index: 569
Printing data for md and index: 570
Printing data for md and index: 571
Printing data for md and index: 572
Printing data for md and index: 573
Printing data for md and index: 574
Printing data for md and index: 575
Printing data for md and index: 576
Printing data for md and index: 577
Printing data for md and index: 578
Printing data for md and index: 579
Printing data for md and index: 580
Printing data for md and index: 581
Printing data for md and index: 582
Printing data for md and index: 583
Printing data for md and index: 584
Printing data for md and index: 585
Printing data for md and index: 586
Printing data for md and index: 587
Printing data for md and index: 588
Printing data for md and index: 589
Printing data for md and index: 590
Printing data for md and index: 591
Printing data for md and index: 592
Printing data for md and index: 593
Printing data for md and index: 594
Printing data for md and index: 595
Printing data for md and index: 596
Printing data for md and index: 597
Printing data for md and index: 598
Printing data for md and index: 599
Printing data for md and index: 600
Printing data for md and index: 601
Printing data for md and index: 602
Printing data for md and index: 603
Printing data for md and index: 604
Printing data for md and index: 605
Printing data for md and index: 606
Printing data for md and index: 607
Printing data for md and index: 608
Printing data for md and index: 609
Printing data for md and index: 610
Printing data for md and index: 611
Printing data for md and index: 612
Printing data for md and index: 613
Printing data for md and index: 614
Printing data for md and index: 615
Printing data for md and index: 616
Printing data for md and index: 617
Printing data for md and index: 618
Printing data for md and index: 619
Printing data for md and index: 620
Printing data for md and index: 621
Printing data for md and index: 622
Printing data for md and index: 623
Printing data for md and index: 624
Printing data for md and index: 625
Printing data for md and index: 626
Printing data for md and index: 627
Printing data for md and index: 628
Printing data for md and index: 629
Printing data for md and index: 630
Printing data for md and index: 631
Printing data for md and index: 632
Printing data for md and index: 633
Printing data for md and index: 634
Printing data for md and index: 635
Printing data for md and index: 636
Printing data for md and index: 637
Printing data for md and index: 638
Printing data for md and index: 639
Printing data for md and index: 640
Printing data for md and index: 641
Printing data for md and index: 642
Printing data for md and index: 643
Printing data for md and index: 644
Printing data for md and index: 645
Printing data for md and index: 646
Printing data for md and index: 647
Printing data for md and index: 648
Printing data for md and index: 649
Printing data for md and index: 650
Printing data for md and index: 651
Printing data for md and index: 652
Printing data for md and index: 653
Printing data for md and index: 654
Printing data for md and index: 655
Printing data for md and index: 656
Printing data for md and index: 657
Printing data for md and index: 658
Printing data for md and index: 659
Printing data for md and index: 660
Printing data for md and index: 661
Printing data for md and index: 662
Printing data for md and index: 663
Printing data for md and index: 664
Printing data for md and index: 665
Printing data for md and index: 666
Printing data for md and index: 667
Printing data for md and index: 668
Printing data for md and index: 669
Printing data for md and index: 670
Printing data for md and index: 671
Printing data for md and index: 672
Printing data for md and index: 673
Printing data for md and index: 674
Printing data for md and index: 675
Printing data for md and index: 676
Printing data for md and index: 677
Printing data for md and index: 678
Printing data for md and index: 679
Printing data for md and index: 680
Printing data for md and index: 681
Printing data for md and index: 682
Printing data for md and index: 683
Printing data for md and index: 684
Printing data for md and index: 685
Printing data for md and index: 686
Printing data for md and index: 687
Printing data for ga and index: 688
Printing data for ga and index: 689
Printing data for ga and index: 690
Printing data for ga and index: 691
Printing data for ga and index: 692
Printing data for ga and index: 693
Printing data for ga and index: 694
Printing data for ga and index: 695
Printing data for ga and index: 696
Printing data for ga and index: 697
Printing data for ga and index: 698
Printing data for ga and index: 699
Printing data for ga and index: 700
Printing data for ga and index: 701
Printing data for ga and index: 702
Printing data for ga and index: 703
Printing data for ga and index: 704
Printing data for ga and index: 705
Printing data for ga and index: 706
Printing data for ga and index: 707
Printing data for ga and index: 708
Printing data for ga and index: 709
Printing data for ga and index: 710
Printing data for ga and index: 711
Printing data for ga and index: 712
Printing data for ga and index: 713
Printing data for ga and index: 714
Printing data for ga and index: 715
Printing data for ga and index: 716
Printing data for ga and index: 717
Printing data for ga and index: 718
Printing data for ga and index: 719
Printing data for ga and index: 720
Printing data for ga and index: 721
Printing data for ga and index: 722

Printing data for ga and index: 723
Printing data for ga and index: 724
Printing data for ga and index: 725
Printing data for ga and index: 726
Printing data for ga and index: 727
Printing data for ga and index: 728
Printing data for ga and index: 729
Printing data for ga and index: 730
Printing data for ga and index: 731
Printing data for ga and index: 732
Printing data for ga and index: 733
Printing data for ga and index: 734
Printing data for ga and index: 735
Printing data for ga and index: 736
Printing data for ga and index: 737
Printing data for ga and index: 738
Printing data for ga and index: 739
Printing data for ga and index: 740
Printing data for ga and index: 741
Printing data for ga and index: 742
Printing data for ga and index: 743
Printing data for ga and index: 744
Printing data for ga and index: 745
Printing data for ga and index: 746
Printing data for ga and index: 747
Printing data for ga and index: 748
Printing data for ga and index: 749
Printing data for ga and index: 750
Printing data for ga and index: 751
Printing data for ga and index: 752
Printing data for ga and index: 753
Printing data for ga and index: 754
Printing data for ga and index: 755
Printing data for ga and index: 756
Printing data for ga and index: 757
Printing data for ga and index: 758
Printing data for ga and index: 759
Printing data for ga and index: 760
Printing data for ga and index: 761
Printing data for ga and index: 762
Printing data for ga and index: 763
Printing data for ga and index: 764
Printing data for ga and index: 765
Printing data for ga and index: 766
Printing data for ga and index: 767
Printing data for ga and index: 768
Printing data for ga and index: 769
Printing data for ga and index: 770
Printing data for ga and index: 771
Printing data for ga and index: 772
Printing data for ga and index: 773
Printing data for ga and index: 774
Printing data for ga and index: 775
Printing data for ga and index: 776
Printing data for ga and index: 777
Printing data for ga and index: 778
Printing data for ga and index: 779
Printing data for ga and index: 780
Printing data for ga and index: 781
Printing data for ga and index: 782
Printing data for ga and index: 783
Printing data for ga and index: 784
Printing data for ga and index: 785
Printing data for ga and index: 786
Printing data for ga and index: 787
Printing data for ga and index: 788
Printing data for ga and index: 789
Printing data for ga and index: 790
Printing data for ga and index: 791
Printing data for ga and index: 792
Printing data for ga and index: 793
Printing data for ga and index: 794
Printing data for ga and index: 795
Printing data for ga and index: 796
Printing data for ga and index: 797
Printing data for ga and index: 798
Printing data for ga and index: 799
Printing data for ga and index: 800
Printing data for ga and index: 801
Printing data for ga and index: 802
Printing data for ga and index: 803
Printing data for ga and index: 804
Printing data for ga and index: 805
Printing data for ga and index: 806
Printing data for ga and index: 807
Printing data for ga and index: 808
Printing data for ga and index: 809
Printing data for ga and index: 810
Printing data for ga and index: 811
Printing data for ga and index: 812
Printing data for ga and index: 813
Printing data for ga and index: 814
Printing data for ga and index: 815
Printing data for ga and index: 816
Printing data for ga and index: 817
Printing data for ga and index: 818
Printing data for ga and index: 819
Printing data for ga and index: 820
Printing data for ga and index: 821
Printing data for ga and index: 822
Printing data for ga and index: 823
Printing data for ga and index: 824
Printing data for ga and index: 825
Printing data for ga and index: 826
Printing data for ga and index: 827
Printing data for ga and index: 828
Printing data for ga and index: 829
Printing data for ga and index: 830
Printing data for ga and index: 831
Printing data for ga and index: 832
Printing data for ga and index: 833
Printing data for ga and index: 834
Printing data for ga and index: 835
Printing data for ga and index: 836
Printing data for ga and index: 837
Printing data for ga and index: 838
Printing data for ga and index: 839
Printing data for ga and index: 840
Printing data for ga and index: 841
Printing data for ga and index: 842
Printing data for ga and index: 843
Printing data for ga and index: 844
Printing data for ga and index: 845
Printing data for ga and index: 846
Printing data for ga and index: 847
Printing data for ga and index: 848
Printing data for ga and index: 849
Printing data for ga and index: 850
Printing data for ga and index: 851
Printing data for ga and index: 852
Printing data for ga and index: 853
Printing data for ga and index: 854
Printing data for ga and index: 855
Printing data for ga and index: 856
Printing data for ga and index: 857
Printing data for ga and index: 858
Printing data for ga and index: 859
Printing data for ga and index: 860
Printing data for fl and index: 861
Printing data for fl and index: 862
Printing data for fl and index: 863
Printing data for fl and index: 864
Printing data for fl and index: 865
Printing data for fl and index: 866
Printing data for fl and index: 867
Printing data for fl and index: 868
Printing data for fl and index: 869
Printing data for fl and index: 870
Printing data for fl and index: 871
Printing data for fl and index: 872
Printing data for fl and index: 873
Printing data for fl and index: 874
Printing data for fl and index: 875
Printing data for fl and index: 876
Printing data for fl and index: 877
Printing data for fl and index: 878
Printing data for fl and index: 879
Printing data for fl and index: 880
Printing data for fl and index: 881
Printing data for fl and index: 882
Printing data for fl and index: 883
Printing data for fl and index: 884
Printing data for fl and index: 885
Printing data for fl and index: 886
Printing data for fl and index: 887
Printing data for fl and index: 888
Printing data for fl and index: 889
Printing data for fl and index: 890
Printing data for fl and index: 891
Printing data for fl and index: 892
Printing data for fl and index: 893
Printing data for fl and index: 894
Printing data for fl and index: 895
Printing data for fl and index: 896
Printing data for fl and index: 897
Printing data for fl and index: 898
Printing data for fl and index: 899
Printing data for fl and index: 900
Printing data for fl and index: 901
Printing data for fl and index: 902
Printing data for fl and index: 903
Printing data for fl and index: 904
Printing data for fl and index: 905
Printing data for fl and index: 906
Printing data for fl and index: 907
Printing data for fl and index: 908
Printing data for fl and index: 909
Printing data for fl and index: 910
Printing data for fl and index: 911
Printing data for fl and index: 912
Printing data for fl and index: 913
Printing data for fl and index: 914
Printing data for fl and index: 915
Printing data for fl and index: 916
Printing data for fl and index: 917
Printing data for fl and index: 918
Printing data for fl and index: 919
Printing data for fl and index: 920
Printing data for fl and index: 921
Printing data for fl and index: 922
Printing data for fl and index: 923
Printing data for fl and index: 924
Printing data for fl and index: 925
Printing data for fl and index: 926
Printing data for fl and index: 927
Printing data for fl and index: 928
Printing data for fl and index: 929
Printing data for fl and index: 930
Printing data for fl and index: 931
Printing data for fl and index: 932
Printing data for fl and index: 933
Printing data for fl and index: 934
Printing data for fl and index: 935
Printing data for fl and index: 936
Printing data for fl and index: 937
Printing data for fl and index: 938
Printing data for fl and index: 939
Printing data for fl and index: 940
Printing data for fl and index: 941
Printing data for fl and index: 942
Printing data for fl and index: 943
Printing data for fl and index: 944
Printing data for fl and index: 945
Printing data for fl and index: 946
Printing data for fl and index: 947
Printing data for fl and index: 948
Printing data for fl and index: 949
Printing data for fl and index: 950
Printing data for fl and index: 951
Printing data for fl and index: 952
Printing data for fl and index: 953
Printing data for fl and index: 954
Printing data for fl and index: 955
Printing data for fl and index: 956
Printing data for fl and index: 957
Printing data for fl and index: 958
Printing data for fl and index: 959
Printing data for fl and index: 960
Printing data for fl and index: 961
Printing data for fl and index: 962
Printing data for fl and index: 963
Printing data for fl and index: 964
Printing data for fl and index: 965
Printing data for fl and index: 966
Printing data for fl and index: 967
Printing data for fl and index: 968

Printing data for fl and index: 969
Printing data for fl and index: 970
Printing data for fl and index: 971
Printing data for fl and index: 972
Printing data for fl and index: 973
Printing data for fl and index: 974
Printing data for fl and index: 975
Printing data for fl and index: 976
Printing data for fl and index: 977
Printing data for fl and index: 978
Printing data for fl and index: 979
Printing data for fl and index: 980
Printing data for fl and index: 981
Printing data for fl and index: 982
Printing data for fl and index: 983
Printing data for fl and index: 984
Printing data for fl and index: 985
Printing data for fl and index: 986
Printing data for fl and index: 987
Printing data for fl and index: 988
Printing data for fl and index: 989
Printing data for fl and index: 990
Printing data for fl and index: 991
Printing data for fl and index: 992
Printing data for fl and index: 993
Printing data for fl and index: 994
Printing data for fl and index: 995
Printing data for fl and index: 996
Printing data for fl and index: 997
Printing data for fl and index: 998
Printing data for fl and index: 999
Printing data for fl and index: 1000
Printing data for fl and index: 1001
Printing data for fl and index: 1002
Printing data for fl and index: 1003
Printing data for fl and index: 1004
Printing data for fl and index: 1005
Printing data for fl and index: 1006
Printing data for fl and index: 1007
Printing data for fl and index: 1008
Printing data for fl and index: 1009
Printing data for fl and index: 1010
Printing data for fl and index: 1011
Printing data for fl and index: 1012
Printing data for fl and index: 1013
Printing data for fl and index: 1014
Printing data for fl and index: 1015
Printing data for fl and index: 1016
Printing data for fl and index: 1017
Printing data for fl and index: 1018
Printing data for fl and index: 1019
Printing data for fl and index: 1020
Printing data for fl and index: 1021
Printing data for fl and index: 1022
Printing data for fl and index: 1023
Printing data for fl and index: 1024
Printing data for fl and index: 1025
Printing data for fl and index: 1026
Printing data for fl and index: 1027
Printing data for fl and index: 1028
Printing data for fl and index: 1029
Printing data for fl and index: 1030
Printing data for fl and index: 1031
Printing data for fl and index: 1032
Printing data for fl and index: 1033

In [4]:
covid_df

,Date,State,Positive,Positive Increase,Death Increase,Death Confirmed,Death Probable,Hospitalized,Negative,Recovered,Total,Total Test Results
0,20200823,CA,663669.0,6777.0,146.0,12134.0,NaN,NaN,9877362.0,NaN,10541031.0,10541031.0
1,20200822,CA,656892.0,6556.0,167.0,11988.0,NaN,NaN,9779460.0,NaN,10436352.0,10436352.0
2,20200821,CA,650336.0,5585.0,135.0,11821.0,NaN,NaN,9679036.0,NaN,10329372.0,10329372.0
3,20200820,CA,644751.0,5920.0,163.0,11686.0,NaN,NaN,9583215.0,NaN,10227966.0,10227966.0
4,20200819,CA,638831.0,6164.0,181.0,11523.0,NaN,NaN,9501852.0,NaN,10140683.0,10140683.0
...,...,...,...,...,...,...,...,...,...,...,...,...
1029,20200308,FL,17.0,3.0,0.0,NaN,NaN,NaN,118.0,NaN,243.0,135.0
1030,20200307,FL,14.0,5.0,0.0,NaN,NaN,NaN,100.0,NaN,202.0,114.0
1031,20200306,FL,9.0,0.0,0.0,NaN,NaN,NaN,55.0,NaN,115.0,64.0
1032,20200305,FL,9.0,7.0,0.0,NaN,NaN,NaN,31.0,NaN,109.0,40.0
1033,20200304,FL,2.0,0.0,0.0,NaN,NaN,NaN,24.0,NaN,42.0,26.0

In [5]:
test = covid_df.copy()

In [6]:
test["Date Format"] = ""

In [7]:
test["Date Format"] = pd.to_datetime(test["Date"], format="%Y%m%d")

In [8]:
test["weeknum"] = ""

In [50]:
test["weeknum"] = test["Date Format"].dt.isocalendar().week

In [51]:
test.to_csv(output_data, index=False)

In [53]:
test_group_edit = test.rename(columns = {"State":"Code"})
test_group_edit

,Date,Code,Positive,Positive Increase,Death Increase,Death Confirmed,Death Probable,Hospitalized,Negative,Recovered,Total,Total Test Results,Date Format,weeknum
0,20200823,CA,663669.0,6777.0,146.0,12134.0,NaN,NaN,9877362.0,NaN,10541031.0,10541031.0,2020-08-23,34
1,20200822,CA,656892.0,6556.0,167.0,11988.0,NaN,NaN,9779460.0,NaN,10436352.0,10436352.0,2020-08-22,34
2,20200821,CA,650336.0,5585.0,135.0,11821.0,NaN,NaN,9679036.0,NaN,10329372.0,10329372.0,2020-08-21,34
3,20200820,CA,644751.0,5920.0,163.0,11686.0,NaN,NaN,9583215.0,NaN,10227966.0,10227966.0,2020-08-20,34
4,20200819,CA,638831.0,6164.0,181.0,11523.0,NaN,NaN,9501852.0,NaN,10140683.0,10140683.0,2020-08-19,34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,20200308,FL,17.0,3.0,0.0,NaN,NaN,NaN,118.0,NaN,243.0,135.0,2020-03-08,10
1030,20200307,FL,14.0,5.0,0.0,NaN,NaN,NaN,100.0,NaN,202.0,114.0,2020-03-07,10
1031,20200306,FL,9.0,0.0,0.0,NaN,NaN,NaN,55.0,NaN,115.0,64.0,2020-03-06,10
1032,20200305,FL,9.0,7.0,0.0,NaN,NaN,NaN,31.0,NaN,109.0,40.0,2020-03-05,10
1033,20200304,FL,2.0,0.0,0.0,NaN,NaN,NaN,24.0,NaN,42.0,26.0,2020-03-04,10

In [54]:
merge_group = pd.merge(test_group_edit, state_df, on = 'Code', how = 'left')
merge_group

,Date,Code,Positive,Positive Increase,Death Increase,Death Confirmed,Death Probable,Hospitalized,Negative,Recovered,Total,Total Test Results,Date Format,weeknum,State,Abbrev
0,20200823,CA,663669.0,6777.0,146.0,12134.0,NaN,NaN,9877362.0,NaN,10541031.0,10541031.0,2020-08-23,34,California,Calif.
1,20200822,CA,656892.0,6556.0,167.0,11988.0,NaN,NaN,9779460.0,NaN,10436352.0,10436352.0,2020-08-22,34,California,Calif.
2,20200821,CA,650336.0,5585.0,135.0,11821.0,NaN,NaN,9679036.0,NaN,10329372.0,10329372.0,2020-08-21,34,California,Calif.
3,20200820,CA,644751.0,5920.0,163.0,11686.0,NaN,NaN,9583215.0,NaN,10227966.0,10227966.0,2020-08-20,34,California,Calif.
4,20200819,CA,638831.0,6164.0,181.0,11523.0,NaN,NaN,9501852.0,NaN,10140683.0,10140683.0,2020-08-19,34,California,Calif.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,20200308,FL,17.0,3.0,0.0,NaN,NaN,NaN,118.0,NaN,243.0,135.0,2020-03-08,10,Florida,Fla.
1030,20200307,FL,14.0,5.0,0.0,NaN,NaN,NaN,100.0,NaN,202.0,114.0,2020-03-07,10,Florida,Fla.
1031,20200306,FL,9.0,0.0,0.0,NaN,NaN,NaN,55.0,NaN,115.0,64.0,2020-03-06,10,Florida,Fla.
1032,20200305,FL,9.0,7.0,0.0,NaN,NaN,NaN,31.0,NaN,109.0,40.0,2020-03-05,10,Florida,Fla.
1033,20200304,FL,2.0,0.0,0.0,NaN,NaN,NaN,24.0,NaN,42.0,26.0,2020-03-04,10,Florida,Fla.

In [61]:
merge_group_df = merge_group.groupby(['State','weeknum'])["Positive"].mean()
merge_group_df

State       weeknum
California  10             64.600000
            11            193.285714
            12            890.142857
            13           3346.571429
            14           9634.285714
                           ...
Texas       30         359177.714286
            31         411074.000000
            32         466133.714286
            33         513835.000000
            34         561607.571429
Name: Positive, Length: 150, dtype: float64

In [62]:
test_group_new = pd.DataFrame(merge_group_df)
test_group_new

                         Positive
State      weeknum
California 10           64.600000
           11          193.285714
           12          890.142857
           13         3346.571429
           14         9634.285714
...                           ...
Texas      30       359177.714286
           31       411074.000000
           32       466133.714286
           33       513835.000000
           34       561607.571429

[150 rows x 1 columns]

In [57]:
state_df = pd.read_csv("Resources/state_abbrev.csv")

In [58]:
state_df.head()

        State  Abbrev Code
0     Alabama    Ala.   AL
1      Alaska  Alaska   AK
2     Arizona   Ariz.   AZ
3    Arkansas    Ark.   AR
4  California  Calif.   CA

In [24]:
ad_df = pd.read_csv("output_data/ad_all_df (1).csv")

In [25]:
ad_df

         State  Weeknum      Value
0   California       17  31.200000
1   California       19  29.533333
2   California       20  33.266667
3   California       21  31.166667
4   California       22  33.100000
..         ...      ...        ...
67       Texas       25  31.300000
68       Texas       26  34.933333
69       Texas       27  36.066667
70       Texas       28  39.566667
71       Texas       29  38.366667

[72 rows x 3 columns]

In [ ]:
# import state csv file
# merge covid with state abbreviation based on state abbreviation
# group the week number and get mean
# groupby column